"""empty message

Revision ID: 312d1e87dea4
Revises: f574e959f9fa
Create Date: 2022-11-14 21:01:32.039991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312d1e87dea4'
down_revision = 'f574e959f9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_desc', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'seeking_desc')
    # ### end Alembic commands ###
